/*
 * This source file was generated by the Gradle 'init' task
 */
package hash_table;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HashTableServerTest {
    @Test void appHasAGreeting() {

    }
}
