/*
 * This source file was generated by the Gradle 'init' task
 */
package hash_table;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;

public class App {
    public static void main(String[] args) throws Exception {
        Server server = ServerBuilder.forPort(8005).addService(new HelloServiceImpl()).build().start();

        System.out.println("Server started, listening on " + server.getPort());

        server.awaitTermination();
    }

    static class HelloServiceImpl extends HelloServiceGrpc.HelloServiceImplBase {
        @Override
        public void sayHello(HelloProto.HelloRequest request, StreamObserver<HelloProto.HelloResponse> responseObserver) {
            String message = "Hello, " + request.getName();
            HelloProto.HelloResponse response = HelloProto.HelloResponse.newBuilder().setMessage(message).build();

            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }
}
